#!/bin/sh 

grep -qxF 'dtoverlay=dwc2' /boot/config.txt \
  || echo 'dtoverlay=dwc2' >> /boot/config.txt

grep -qF 'modules-load=dwc2,g_ether' /boot/cmdline.txt \
  || sed -i 's/rootwait/rootwait modules-load=dwc2,g_ether /g' /boot/cmdline.txt

exit 0
