#!/bin/sh

uci -q del firewall.captive
uci set firewall.captive='redirect'
uci set firewall.captive.name='Captive Portal'
uci set firewall.captive.target='DNAT'
uci set firewall.captive.src='lan'
uci set firewall.captive.src_dport='80'
uci set firewall.captive.src_ip='!192.168.1.1'
uci set firewall.captive.dest_ip='192.168.1.1'

uci commit firewall
service firewall restart

exit 0
