#!/bin/sh

echo $0: activate captive portal on port 80 >> /dev/kmsg

[ "`uci get firewall.captive.name`" == "" ] || exit 0 # only enable if not defined

uci -q del firewall.captive
uci set firewall.captive='redirect'
uci set firewall.captive.name='Captive Portal'
uci set firewall.captive.target='DNAT'
uci set firewall.captive.src='lan'
uci set firewall.captive.src_ip='!192.168.1.1'
uci set firewall.captive.src_dport='80'
uci set firewall.captive.src_dip='!192.168.1.1'
uci set firewall.captive.dest='lan'
uci set firewall.captive.dest_ip='192.168.1.1'
uci set firewall.captive.dest_port='8080'

uci -q del firewall.captives
uci set firewall.captives='redirect'
uci set firewall.captives.name='Captive Portal Https'
uci set firewall.captives.target='DNAT'
uci set firewall.captives.src='lan'
uci set firewall.captives.src_ip='!192.168.1.1'
uci set firewall.captives.src_dport='443'
uci set firewall.captives.src_dip='!192.168.1.1'
uci set firewall.captives.dest='lan'
uci set firewall.captives.dest_ip='192.168.1.1'
uci set firewall.captives.dest_port='8443'

uci set uhttpd.captive=uhttpd
uci set uhttpd.captive.home='/www/captive'
uci add_list uhttpd.captive.listen_http='8080'
uci add_list uhttpd.captive.listen_https='8443'
uci add_list uhttpd.captive.interpreter='.cgi=/bin/sh'
uci add_list uhttpd.captive.index_page='redirect.cgi'
uci add_list uhttpd.captive.error_page='/'
uci set uhttpd.captive.cert='/etc/uhttpd.crt'
uci set uhttpd.captive.key='/etc/uhttpd.key'

echo "address=/#/100.64.64.64" >> /etc/dnsmasq.conf

# uci add_list dhcp.lan.dhcp_option='114,http://192.168.1.1'

uci commit firewall
uci commit uhttpd

service uhttpd restart
service firewall restart

exit 0
