#!/bin/sh

echo $0: activate captive portal on port 80 >> /dev/kmsg

[ "`uci get firewall.captive.name`" == "" ] || exit 0 # only enable if not defined

uci -q del firewall.captive
uci set firewall.captive='redirect'
uci set firewall.captive.name='Captive Portal'
uci set firewall.captive.target='DNAT'
uci set firewall.captive.src='lan'
uci set firewall.captive.src_dport='80'
uci set firewall.captive.src_ip='!192.168.1.1'
uci set firewall.captive.dest_ip='192.168.1.1'
uci set firewall.captive.dest_port='81'

uci set uhttpd.captive.home='/www/captive'
uci add_list uhttpd.captive.listen_http='0.0.0.0:81'
uci add_list uhttpd.captive.interpreter='.cgi=/bin/sh'
uci add_list uhttpd.captive.index_page='redirect.cgi'

uci commit firewall
uci commit uhttpd

service uhttpd restart
service firewall restart

exit 0
