#!/bin/sh

echo $0: enable default wifi >> /dev/kmsg

[ "`uci get wireless.@wifi-device[0].disabled`" == "0" ] && exit 0 # only enable if disabled
[ "`uci get wireless.@wifi-iface[0].mode`" == "sta" ] && exit 0   # only enable if not wifi client mode 

uci set wireless.@wifi-device[0].disabled=0
uci set wireless.@wifi-iface[0].disabled="0"
uci set wireless.@wifi-iface[0].ssid="set-me-up"

uci commit wireless

exit 0
